\subsection{Exceptions}

\begin{frame}[t,fragile]{Exceptions}
\begin{itemize}
  \item C++ exception model exhibits differences with other languages.

  \pause\vfill
  \item An exception may be any type.
\begin{lstlisting}
class invalid_time {};
\end{lstlisting}

  \pause\vfill
  \item When a function detects an exceptional situation throws
        (\cppkey{throw}) an exception.
\begin{lstlisting}
void print_velocity(double s, double t) {
  if (t <= 0.0) {
    throw invalid_time{};
  }
  std::println("velocity = {}", s/t);
}
\end{lstlisting}

\end{itemize}
\end{frame}

\begin{frame}[t,fragile]{Exception handling}
\begin{itemize}
  \item Caller may handle an exception with a \cppkey{try}-\cppkey{catch} block.
\begin{lstlisting}
void f() {
  double s = get_space();
  double t = get_time();
  try {
    print_velocity(s,t);
  }
  catch (invalid_time) {
    std::println(std::cerr, "Error: Invalid time\n");
  }
}
\end{lstlisting}
  \vfill\pause
  \item If an exception is not handled $\rightarrow$ it propagates to next level.
\begin{lstlisting}
void f() {
  double s = get_space(), t = get_time();
  print_velocity(s,t);
}
\end{lstlisting}
\end{itemize}
\end{frame}

\begin{frame}[t,fragile]{Standard exceptions}
\begin{itemize}
  \item Several predefined exceptions in the standard library.
    \begin{itemize}
      \item \cppid{out\_of\_range}, \cppid{invalid\_argument}, \ldots
      \item All inheriting from \cppid{exception}.
      \item All have a \cppid{what()} member function.
    \end{itemize}
\end{itemize}
\mode<presentation>{\vspace{-.5em}}
\begin{columns}[T]

\column{.5\textwidth}
\begin{lstlisting}
struct invalid_time : public std::invalid_argument{
  invalid_time() :
    std::invalid_argument{"Invalid time"} {}
};

void print_velocity(double s, double t) {
  if (t <= 0.0) {
    throw invalid_time{};
  }
  std::println("velocity = {}", s/t);
}
\end{lstlisting}

\column{.5\textwidth}
\begin{lstlisting}
int main() try {
  f();
}
catch (std::out_of_range const & e) {
  std::cerr << "Out of range:" << e.what() << "\n";
  return EXIT_FAILURE;
}
catch (std::exception const & e) {
  std::cerr << "Exception: " << e.what() << "\n";
  return EXIT_FAILURE;
}
\end{lstlisting}
\end{columns}

\end{frame}
